name: Upgrade requirements

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.branch }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install script dependency
        run: python -m pip install packaging

      - name: Bump Dockerfile version
        env:
          BRANCH: ${{ github.event.client_payload.branch }}
          LIB_NAME: ${{ github.event.client_payload.lib_name }}
          LIB_VERSION: ${{ github.event.client_payload.lib_vers }}
        run: python .github/scripts/bumpver.py
